// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlgdpabuqiiqmarelntq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZ2RwYWJ1cWlpcW1hcmVsbnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTEyNTMsImV4cCI6MjA3NDMyNzI1M30.3TleLzP2NN8dmxU24qZS6AEut39AzYXVUkYWyU6xeSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});